default:
  image: alpine/git

variables:
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}" 
  no_proxy: "${NO_PROXY}"
  
stages:
  - build
  - test

build:go-build:
  stage: build
  tags:
    - k8s
  image: golang:latest
  before_script:
    - git config --global http."https://${GITLAB_SERVER}".proxy ""
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
    - cd $CI_PROJECT_DIR
  script:
    - echo "This is the CI job that builds monorepo"
    - go build ./...

test:go-unit-tests:
  stage: test
  tags:
    - k8s
  image: golang:latest
  before_script:
    - git config --global http."https://${GITLAB_SERVER}".proxy ""
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
    - cd $CI_PROJECT_DIR
  script:
    - echo "This is the CI job that runs all unit tests"
    - go test ./... -coverprofile=cover.out
    - go tool cover -func cover.out
