name: Go

on:
  push:
    branches: [ insights ]
  pull_request:
    branches: [ insights ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build-cms
      run: make cms-installer

    - name: Build-authservice
      run: make authservice

    - name: Build-hvs
      run: make hvs

    - name: Build-ihub
      run: make ihub

    - name: Build-wpm
      run: make wpm
